[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.dvc
  | mlruns
  | trained_models
  | raw_data
  | analysis
  | \.ipynb_checkpoints
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true
known_first_party = ["src"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".dvc",
    "mlruns",
    "trained_models",
    "raw_data",
    "analysis",
    "__pycache__",
    "**/__pycache__",
    ".ipynb_checkpoints",
    "**/.ipynb_checkpoints"
]
# Если хочешь, чтобы длинные строки остались в отдельных файлах:
# per-file-ignores = [
#   "src/monitoring/api_drift_test.py:E501",
# ]
